services:
  - type: web
    name: pipefy-supabase-ingestor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastAPI:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PIPEFY_TOKEN
        sync: false
      - key: PIPEFY_WEBHOOK_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET_NAME
        value: documents 